version: "3.8"

services:
  server:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - '8080:443'
    # volumes:
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #   - php
    #   - mysql

  # php:
  # mysql:
  # composer:
  # artisan:
  # npm:
      