version: '3.8'

services:

  nginx:
    image: nginx
    pull_policy: never
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - '443:443'
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
      - wordpress

  wordpress:
    image: wordpress
    pull_policy: never
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile:  Dockerfile
    # ports:
    #   - "9000:9000"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - ./.env
    expose:
      - 9000
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    pull_policy: never
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - ./.env
    expose:
      - 3306

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/dahkang/data/db_data'
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/dahkang/data/wp_data'

networks:
  inception:
    driver: bridge