# version: "3.8"

# services:
#   server:
#     build:
#       context: requirements/nginx
#       dockerfile: Dockerfile
#     ports:
#       - '8080:443'
    # volumes:
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #   - php
    #   - mysql

  # php:
  # mysql:
  # composer:
  # artisan:
  # npm:

version: '3.8'

services:
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile:  Dockerfile
    ports:
      - "8080:9000"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      